### ISSUE TITLE
飞书测试可接收到消息-Job构建未收到消息通知

### ISSUE THREAD

**Issue by DanielZhui** [721806280/lark-notice-plugin#111]
jenkins 版本：2.440.2
lark 下载最新版： 2.0， 下载地址：https://github.com/721806280/lark-notice-plugin/releases

**Comment by 721806280** [comment]
参考[文档常见问题](https://721806280.github.io/lark-notice-plugin-doc/guide/FAQ.html#_3-%E6%97%A0%E6%B3%95%E5%8F%91%E9%80%81%E6%B6%88%E6%81%AF%E9%80%9A%E7%9F%A5)排查

**Comment by DanielZhui** [comment]
安装后重启，且通知机制全部勾选 还是不行

**Comment by 721806280** [comment]
@DanielZhui  加微: 721806280
