### ISSUE TITLE
更新jenkins到2.455后 env.BUILD_USER为null

### ISSUE THREAD

**Issue by B1ackg0d** [721806280/lark-notice-plugin#116]
RT. 飞书发出来的消息该字段一直是null, 靓仔能帮忙看看吗
![image](https://github.com/721806280/lark-notice-plugin/assets/50610732/b5f48719-3258-4b4e-bd30-c59ab417231a)

**Comment by 721806280** [comment]
检查是否已登陆JENKINS?
