### ISSUE TITLE
自定义变量无法使用

### ISSUE THREAD

**Issue by Linuxstyle** [721806280/lark-notice-plugin#124]
Jenkins：
     2.452.2
插件中自定义变量：
      EXECUTOR_NAME | 构建人姓名
      EXECUTOR_MOBILE | 构建人手机号码
      EXECUTOR_OPENID | 构建人OPENID

通过${env.EXECUTOR_NAME}、${env.EXECUTOR_MOBILE}、${env.EXECUTOR_OPENID}无法获取到

**Comment by 721806280** [comment]
[pipeline参考](https://721806280.github.io/lark-notice-plugin-doc/guide/feature/lark/pipeline.html)
