### ISSUE TITLE
希望能在通知标题显示任务失败与否

### ISSUE THREAD

**Issue by xgdgsc** [721806280/lark-notice-plugin#160]
希望能在通知标题显示任务失败与否，因为在智能手表的飞书通知上，可能只显示标题，这样目前的方式就看不出来是失败还是成功，如果能在标题显示就不用每条都去飞书里看了。

**Comment by 721806280** [comment]
@xgdgsc 在任务设置中找到机器人配置，然后自定义标题即可。这样可以个性化您的信息展示。
![WeChat5af3248264dbb2fa137a750a30fa0372](https://github.com/user-attachments/assets/7c98319c-eb42-4d84-ad6f-a96275270d7c)

**Comment by xgdgsc** [comment]
知道了,但默认更好
