### ISSUE TITLE
No subject alternative DNS name matching open.feishu.cn found.

### ISSUE THREAD

**Issue by zpfhyj** [721806280/lark-notice-plugin#99]
jenkins版本2.446， 刚安装完成后，点击测试。发送测试消息没问题。在项目后配置好机器人发布项目也可以正常发送消息。但是隔一段时间后就无法发送飞书消息了，详细报错如下截图
在飞书插件配置中点击测试报错如下图
![image](https://github.com/721806280/lark-notice-plugin/assets/24708763/1b2ead81-0130-4649-9be0-faee58ab86b5)

在项目构建发送消息的报错如下图
![image](https://github.com/721806280/lark-notice-plugin/assets/24708763/0cfa3f22-991e-464c-b06a-ae434a9e1f67)

**Comment by 721806280** [comment]
请更新[插件](https://github.com/721806280/lark-notice-plugin/releases/download/v2.0.0/lark-notice.hpi)后重试～

**Comment by 721806280** [comment]
#98
